/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculator;

/**
 *
 * @author audreykellogg
 */
public class CalculatorFrame extends javax.swing.JFrame {
    private Operation operation;

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnClear = new javax.swing.JButton();
        jbtnChangeSign = new javax.swing.JButton();
        jbtnPercent = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnSeven = new javax.swing.JButton();
        jbtnEight = new javax.swing.JButton();
        jbtnNine = new javax.swing.JButton();
        jbtnMultiply = new javax.swing.JButton();
        jbtnFour = new javax.swing.JButton();
        jbtnFive = new javax.swing.JButton();
        jbtnSix = new javax.swing.JButton();
        jbtnSubtraction = new javax.swing.JButton();
        jbtnOne = new javax.swing.JButton();
        jbtnTwo = new javax.swing.JButton();
        jbtnThree = new javax.swing.JButton();
        jbtnAddition = new javax.swing.JButton();
        jlblZero = new javax.swing.JButton();
        jbtnPeriod = new javax.swing.JButton();
        jbtnBackspace = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlblOperand = new javax.swing.JLabel();
        jlblOperand1 = new javax.swing.JLabel();
        jlblOperation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnClear.setBackground(new java.awt.Color(102, 255, 204));
        jbtnClear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnClear.setText("AC");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnChangeSign.setBackground(new java.awt.Color(102, 255, 204));
        jbtnChangeSign.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnChangeSign.setText("+/-");
        jbtnChangeSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeSignActionPerformed(evt);
            }
        });

        jbtnPercent.setBackground(new java.awt.Color(102, 255, 204));
        jbtnPercent.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnPercent.setText("%");
        jbtnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPercentActionPerformed(evt);
            }
        });

        jbtnDivide.setBackground(new java.awt.Color(102, 255, 204));
        jbtnDivide.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnDivide.setText("÷ ");
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });

        jbtnSeven.setBackground(new java.awt.Color(102, 255, 204));
        jbtnSeven.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnSeven.setText("7");
        jbtnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSevenActionPerformed(evt);
            }
        });

        jbtnEight.setBackground(new java.awt.Color(102, 255, 204));
        jbtnEight.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnEight.setText("8");
        jbtnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEightActionPerformed(evt);
            }
        });

        jbtnNine.setBackground(new java.awt.Color(102, 255, 204));
        jbtnNine.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnNine.setText("9");
        jbtnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNineActionPerformed(evt);
            }
        });

        jbtnMultiply.setBackground(new java.awt.Color(102, 255, 204));
        jbtnMultiply.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnMultiply.setText("x");
        jbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplyActionPerformed(evt);
            }
        });

        jbtnFour.setBackground(new java.awt.Color(102, 255, 204));
        jbtnFour.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnFour.setText("4");
        jbtnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFourActionPerformed(evt);
            }
        });

        jbtnFive.setBackground(new java.awt.Color(102, 255, 204));
        jbtnFive.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnFive.setText("5");
        jbtnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiveActionPerformed(evt);
            }
        });

        jbtnSix.setBackground(new java.awt.Color(102, 255, 204));
        jbtnSix.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnSix.setText("6");
        jbtnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSixActionPerformed(evt);
            }
        });

        jbtnSubtraction.setBackground(new java.awt.Color(102, 255, 204));
        jbtnSubtraction.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnSubtraction.setText("-");
        jbtnSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubtractionActionPerformed(evt);
            }
        });

        jbtnOne.setBackground(new java.awt.Color(102, 255, 204));
        jbtnOne.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnOne.setText("1");
        jbtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOneActionPerformed(evt);
            }
        });

        jbtnTwo.setBackground(new java.awt.Color(102, 255, 204));
        jbtnTwo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnTwo.setText("2");
        jbtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTwoActionPerformed(evt);
            }
        });

        jbtnThree.setBackground(new java.awt.Color(102, 255, 204));
        jbtnThree.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnThree.setText("3");
        jbtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThreeActionPerformed(evt);
            }
        });

        jbtnAddition.setBackground(new java.awt.Color(102, 255, 204));
        jbtnAddition.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnAddition.setText("+");
        jbtnAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdditionActionPerformed(evt);
            }
        });

        jlblZero.setBackground(new java.awt.Color(102, 255, 204));
        jlblZero.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlblZero.setText("0");
        jlblZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblZeroActionPerformed(evt);
            }
        });

        jbtnPeriod.setBackground(new java.awt.Color(102, 255, 204));
        jbtnPeriod.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnPeriod.setText(".");
        jbtnPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPeriodActionPerformed(evt);
            }
        });

        jbtnBackspace.setBackground(new java.awt.Color(102, 255, 204));
        jbtnBackspace.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnBackspace.setText("<-");
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });

        jbtnEquals.setBackground(new java.awt.Color(102, 255, 204));
        jbtnEquals.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtnEquals.setText("=");
        jbtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jlblOperand.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlblOperand.setForeground(new java.awt.Color(255, 255, 255));
        jlblOperand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlblOperand1.setForeground(new java.awt.Color(255, 255, 255));
        jlblOperand1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlblOperation.setForeground(new java.awt.Color(255, 255, 255));
        jlblOperation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblOperation.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblOperand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblOperand1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblOperand1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblOperation, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
       clear();// TODO add your handling code here:
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnChangeSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeSignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnChangeSignActionPerformed

    private void jbtnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPercentActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSevenActionPerformed
        appendValue("7");// TODO add your handling code here:
    }//GEN-LAST:event_jbtnSevenActionPerformed

    private void jbtnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEightActionPerformed
        appendValue("8");// TODO add your handling code here:
    }//GEN-LAST:event_jbtnEightActionPerformed

    private void jbtnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNineActionPerformed
        appendValue("9");// TODO add your handling code here:
    }//GEN-LAST:event_jbtnNineActionPerformed

    private void jbtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnMultiplyActionPerformed

    private void jbtnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFourActionPerformed
        appendValue("4"); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFourActionPerformed

    private void jbtnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiveActionPerformed
       appendValue("5"); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFiveActionPerformed

    private void jbtnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSixActionPerformed
        appendValue("6");// TODO add your handling code here:
    }//GEN-LAST:event_jbtnSixActionPerformed

    private void jbtnSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubtractionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSubtractionActionPerformed

    private void jbtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOneActionPerformed
        appendValue("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnOneActionPerformed

    private void jbtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTwoActionPerformed
       appendValue("2"); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTwoActionPerformed

    private void jbtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThreeActionPerformed
       appendValue("3"); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnThreeActionPerformed

    private void jbtnAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdditionActionPerformed
        //store operand
        //store the operation
       //clear the screen 
        jlblOperand1.setText(jlblOperand.getText());
        clear();
        setOperation(Operation.ADDITION);
    }//GEN-LAST:event_jbtnAdditionActionPerformed

    private void jlblZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblZeroActionPerformed
        appendValue("0");       // TODO add your handling code here:
    }//GEN-LAST:event_jlblZeroActionPerformed

    private void jbtnPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPeriodActionPerformed
       appendValue("."); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPeriodActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualsActionPerformed
        //add numbers
        //put result in screen
        //clear operand 1 label
        //reset operation to none
        switch (operation) {
            case ADDITION: 
                double result = Double.parseDouble(jlblOperand1.getText()) + Double.parseDouble(jlblOperand.getText());
                jlblOperand.setText(String.valueOf(result));
                jlblOperand1.setText("");
                setOperation(Operation.NONE);
                
                
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jbtnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnAddition;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnChangeSign;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnEight;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnFive;
    private javax.swing.JButton jbtnFour;
    private javax.swing.JButton jbtnMultiply;
    private javax.swing.JButton jbtnNine;
    private javax.swing.JButton jbtnOne;
    private javax.swing.JButton jbtnPercent;
    private javax.swing.JButton jbtnPeriod;
    private javax.swing.JButton jbtnSeven;
    private javax.swing.JButton jbtnSix;
    private javax.swing.JButton jbtnSubtraction;
    private javax.swing.JButton jbtnThree;
    private javax.swing.JButton jbtnTwo;
    private javax.swing.JLabel jlblOperand;
    private javax.swing.JLabel jlblOperand1;
    private javax.swing.JLabel jlblOperation;
    private javax.swing.JButton jlblZero;
    // End of variables declaration//GEN-END:variables

    private void appendValue(String value) {
        if ((jlblOperand.getText().equals("0") && (!value.equals(".")))) {
            clear();
        }
        
        if (value.equals(".") && (jlblOperand.getText().isEmpty())) {
            value = "0" + value;
        }
        
        
        jlblOperand.setText(jlblOperand.getText() + value);
    }

    private void clear() {
        jlblOperand.setText("");
    }

    private void setOperation(Operation operation) {
        this.operation = operation;
        jlblOperation.setText(this.operation.getLabel());
    }
}
